apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    name: mypod
spec:
  containers:
  - name: webserver
    image: ubuntu
    workingDir: /tmp/mypod
    command: ["python3", "-m", "http.server", "80"]
    ports:
    - containerPort: 80
    volumeMounts:
    - name: htdocs
      mountPath: /tmp/mypod
  - name: busybox
    image: sttts/busybox-curl
    tty: true
    stdin: true
    volumeMounts:
    - name: htdocs
      mountPath: /tmp/mypod
  volumes:
  - name: htdocs
    hostPath:
      path: /tmp/mypod
